version: '3.7'
services:
  web:
    container_name: carford-backend
    build: .
    volumes:
      - .:/opt/carford
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: root
      POSTGRES_DB: carford